### ISSUE TITLE
engineio companion

### ISSUE THREAD

**Issue by deepak1556** [mbenford/ngSocketIO#1]
https://github.com/deepak1556/ngEngineIO i wrote this as a companion to ngSocketIO for people who would like to use engineio based on your work, would you care trying it out. Thanks.

**Comment by mbenford** [comment]
Hi @deepak1556.

Nice work! I don't know EngineIO very much so I'm afraid I can't give it the try it deserves. Based solely on the code, I think you could write more tests to cover the features you have added that don't exist in ngSocketIO. 

Kind regards.
